apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qi-apps.vxApi.fullname" . }}
  labels:
    {{- include "qi-apps.labels" . | nindent 4 }}
    {{- include "qi-apps.vxApi.selectorLabels" . | nindent 4 }}
spec:
  {{- if not .Values.vxApi.autoscaling.enabled }}
  replicas: {{ .Values.vxApi.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "qi-apps.vxApi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.vxApi.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "qi-apps.vxApi.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.vxApi.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "qi-apps.vxApi.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.vxApi.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.vxApi.securityContext | nindent 12 }}
          image: "{{ .Values.vxApi.image.repository }}:{{ .Values.vxApi.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.vxApi.image.pullPolicy }}
          env:
            - name: API_PORT
              value: "80"
          envFrom:
          - configMapRef:
              name: vx-api-env
          - secretRef:
              name: {{ .Values.vxApi.config.secretName }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.vxApi.resources | nindent 12 }}
      {{- with .Values.vxApi.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.vxApi.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.vxApi.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
