{{- if .Values.vxApi.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "qi-apps.vxApi.serviceAccountName" . }}
  labels:
    {{- include "qi-apps.labels" . | nindent 4 }}
  {{- with .Values.vxApi.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
